#!/usr/bin/env node
/**
 * Build static HTML files from Markdown guides.
 *
 * Source: src/pages/{zh,en}/guides/*.md
 * Output: zh/guides/{slug}.html, en/guides/{slug}.html
 *
 * The [slug].astro route reads these HTML files and renders their <main> content
 * inside BaseLayout. The HTML files are "full pages" but only the <main> block
 * is used — everything else (head/nav/footer) is regenerated by Astro.
 *
 * Conversion rules:
 *   - Standard Markdown → HTML (headings, lists, tables, bold, italic, links)
 *   - FAQ paragraphs (Q: ... / A: ...) → <div class="faq-q"> / <div class="faq-a">
 *   - Wrapped in <main class="article-container">
 *
 * Idempotent. Safe to re-run.
 *
 * Usage:
 *   node scripts/build-guides.mjs            # build all .md files
 *   node scripts/build-guides.mjs --dry-run  # print what would change
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const dryRun = process.argv.includes('--dry-run');

// HTML escape for safe text
function esc(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// Inline markdown → HTML (bold, italic, code, links)
function inline(text) {
  // code
  text = text.replace(/`([^`]+)`/g, '<code>$1</code>');
  // bold
  text = text.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  // italic
  text = text.replace(/\*([^*]+)\*/g, '<em>$1</em>');
  // links [text](url)
  text = text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
  return text;
}

// Parse a single markdown file → HTML string
function mdToHtml(md) {
  const lines = md.split('\n');
  const out = [];
  let i = 0;
  let inTable = false;
  let inList = null; // 'ul' | 'ol' | null
  let inCodeBlock = false;
  let codeLang = '';
  let codeBuf = [];

  const closeList = () => {
    if (inList) {
      out.push(`</${inList}>`);
      inList = null;
    }
  };
  const closeTable = () => {
    if (inTable) {
      out.push('</tbody></table>');
      inTable = false;
    }
  };

  while (i < lines.length) {
    const line = lines[i];

    // Code block
    if (line.startsWith('```')) {
      if (!inCodeBlock) {
        closeList();
        closeTable();
        inCodeBlock = true;
        codeLang = line.slice(3).trim();
        codeBuf = [];
      } else {
        const langClass = codeLang ? ` class="language-${esc(codeLang)}"` : '';
        out.push(`<pre${langClass}><code>${esc(codeBuf.join('\n'))}</code></pre>`);
        inCodeBlock = false;
        codeLang = '';
        codeBuf = [];
      }
      i++;
      continue;
    }
    if (inCodeBlock) {
      codeBuf.push(line);
      i++;
      continue;
    }

    // Horizontal rule
    if (line.trim() === '---') {
      closeList();
      closeTable();
      out.push('<hr>');
      i++;
      continue;
    }

    // Headings
    const hMatch = line.match(/^(#{1,6})\s+(.+)$/);
    if (hMatch) {
      closeList();
      closeTable();
      const level = hMatch[1].length;
      const content = inline(esc(hMatch[2]));
      const id = hMatch[2]
        .toLowerCase()
        .replace(/[^\w\s\u4e00-\u9fff-]/g, '')
        .replace(/\s+/g, '-');
      out.push(`<h${level} id="${id}">${content}</h${level}>`);
      i++;
      continue;
    }

    // Table — markdown | col | col |
    if (line.trim().startsWith('|') && line.trim().endsWith('|')) {
      const next = lines[i + 1] || '';
      if (next.match(/^\|[\s-:|]+\|$/)) {
        closeList();
        if (!inTable) {
          const headers = line.split('|').slice(1, -1).map(c => inline(esc(c.trim())));
          out.push('<table><thead><tr>' + headers.map(h => `<th>${h}</th>`).join('') + '</tr></thead><tbody>');
          inTable = true;
        }
        i += 2; // skip header + separator
        continue;
      } else if (inTable) {
        const cells = line.split('|').slice(1, -1).map(c => inline(esc(c.trim())));
        out.push('<tr>' + cells.map(c => `<td>${c}</td>`).join('') + '</tr>');
        i++;
        continue;
      }
    }

    // Lists
    const ulMatch = line.match(/^(\s*)[-*]\s+(.+)$/);
    const olMatch = line.match(/^(\s*)\d+\.\s+(.+)$/);
    if (ulMatch || olMatch) {
      closeTable();
      const tag = ulMatch ? 'ul' : 'ol';
      if (inList !== tag) {
        closeList();
        out.push(`<${tag}>`);
        inList = tag;
      }
      const content = inline(esc((ulMatch || olMatch)[2]));
      out.push(`<li>${content}</li>`);
      i++;
      continue;
    } else {
      closeList();
    }

    // FAQ block: detect Q: ... / A: ... pattern, wrap in <div class="faq-q">/<div class="faq-a">
    const faqQ = line.match(/^\*\*(Q\d*[:：]?\s*[^<*]+?)\*\*\s*$/);
    const faqAInline = line.match(/^\*\*A\d*[:：]?\s*(.+?)\*\*\s*$/);
    const faqALine = line.match(/^A\d*[:：]\s*(.+)$/);

    if (faqQ) {
      closeTable();
      const qText = esc(faqQ[1].replace(/^Q\d*[:：]?\s*/, '').trim());
      out.push(`<div class="faq-q">${inline(qText)}</div>`);
      // Check next line for A:
      const nextLine = lines[i + 1] || '';
      const aMatch = nextLine.match(/^A\d*[:：]?\s*(.+)$/);
      if (aMatch) {
        const aText = inline(esc(aMatch[1].trim()));
        out.push(`<div class="faq-a">${aText}</div>`);
        i += 2;
        continue;
      }
      i++;
      continue;
    }
    if (faqAInline) {
      closeTable();
      const aText = inline(esc(faqAInline[1].trim()));
      out.push(`<div class="faq-a">${aText}</div>`);
      i++;
      continue;
    }
    if (faqALine) {
      closeTable();
      const aText = inline(esc(faqALine[1].trim()));
      out.push(`<div class="faq-a">${aText}</div>`);
      i++;
      continue;
    }

    // Empty line
    if (line.trim() === '') {
      closeList();
      closeTable();
      i++;
      continue;
    }

    // Paragraph
    closeTable();
    out.push(`<p>${inline(esc(line))}</p>`);
    i++;
  }

  closeList();
  closeTable();
  return out.join('\n');
}

// Wrap FAQ sections with optional structure. The [slug].astro route extracts
// <main> content. We use <main> to wrap the body, and let the route extract it.
function wrapHtml(title, bodyHtml, lang) {
  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<title>${esc(title)}</title>
</head>
<body>
<main class="article-container">
${bodyHtml}
</main>
</body>
</html>
`;
}

const targetSlugs = process.argv.slice(2).filter(a => !a.startsWith('--'));

// Build all .md → .html
const langs = ['zh', 'en'];
let touched = 0;
let skipped = 0;

for (const lang of langs) {
  const mdDir = path.join(repoRoot, 'src/pages', lang, 'guides');
  const htmlDir = path.join(repoRoot, lang, 'guides');
  if (!fs.existsSync(mdDir)) continue;
  for (const fn of fs.readdirSync(mdDir)) {
    if (!fn.endsWith('.md')) continue;
    const slug = fn.replace(/\.md$/, '');
    if (targetSlugs.length && !targetSlugs.includes(slug)) continue;

    const mdPath = path.join(mdDir, fn);
    const md = fs.readFileSync(mdPath, 'utf-8');
    const html = mdToHtml(md);

    // Extract H1 for <title>
    const h1Match = md.match(/^#\s+(.+)$/m);
    const title = h1Match ? h1Match[1].trim() : slug;

    const fullHtml = wrapHtml(title, html, lang);
    const outPath = path.join(htmlDir, `${slug}.html`);

    // Skip if unchanged
    let existing = '';
    try { existing = fs.readFileSync(outPath, 'utf-8'); } catch (e) {}
    // Compare only the <main> block — head/foot may differ in title formatting
    const mainMatch = (s) => (s.match(/<main[^>]*>([\s\S]*?)<\/main>/) || ['', ''])[1];
    if (mainMatch(existing).trim() === html.trim()) {
      skipped++;
      continue;
    }

    fs.mkdirSync(htmlDir, { recursive: true });
    if (!dryRun) fs.writeFileSync(outPath, fullHtml, 'utf-8');
    touched++;
    console.log(`  ${lang}/${slug}: ${html.length} chars`);
  }
}

console.log(`\n📊 ${dryRun ? 'Would update' : 'Updated'}: ${touched}, skipped (already up to date): ${skipped}`);