import { defineCollection, z } from 'astro:content';
import { file } from 'astro/loaders';

const toolSchema = z.object({
  slug: z.string(),
  name_zh: z.string(),
  name_en: z.string(),
  category: z.enum(['video', 'image', 'llm', 'coding', 'ai-assistant', 'audio']),
  category_zh: z.string(),
  category_en: z.string(),
  type: z.string().optional().default('tool'),
  official_url: z.string(),
  company_zh: z.string().optional().default(''),
  company_en: z.string().optional().default(''),
  description_zh: z.string(),
  description_en: z.string(),
  free_credits: z.object({
    type: z.string().optional().default(''),
    amount: z.string().optional().default(''),
    amount_en: z.string().optional().default(''),
    duration: z.string().optional().default(''),
    duration_en: z.string().optional().default(''),
    resolution: z.string().optional().default(''),
    resolution_en: z.string().optional().default(''),
    watermark: z.union([z.string(), z.boolean()]).optional().default(''),
    watermark_en: z.union([z.string(), z.boolean()]).optional().default(''),
    commercial_use: z.union([z.string(), z.boolean()]).optional().default(''),
    commercial_use_en: z.union([z.string(), z.boolean()]).optional().default(''),
    reset: z.string().optional().default(''),
    reset_en: z.string().optional().default(''),
    models: z.string().optional().default(''),
    models_en: z.string().optional().default(''),
    daily_limit: z.string().optional().default(''),
    daily_limit_en: z.string().optional().default(''),
  }).optional(),
  activity: z.object({
    has_activity: z.boolean().optional().default(false),
    activity_type: z.string().optional().default(''),
    activity_text_zh: z.string().optional().default(''),
    activity_text_en: z.string().optional().default(''),
    activity_url: z.string().optional().default(''),
    activity_deadline: z.string().optional().default(''),
  }).optional(),
  features_zh: z.array(z.string()).optional().default([]),
  features_en: z.array(z.string()).optional().default([]),
  pros_zh: z.array(z.string()).optional().default([]),
  pros_en: z.array(z.string()).optional().default([]),
  cons_zh: z.array(z.string()).optional().default([]),
  cons_en: z.array(z.string()).optional().default([]),
  tips_zh: z.array(z.string()).optional().default([]),
  tips_en: z.array(z.string()).optional().default([]),
  rating: z.number().min(0).max(5).optional().default(4),
  paid_from: z.string().optional().default(''),
  paid_from_en: z.string().optional().default(''),
  last_updated: z.string().optional().default(''),
  free_level: z.string().optional().default(''),
  free_note: z.string().optional().default(''),
  free_note_en: z.string().optional().default(''),
  images: z.array(z.string()).optional().default([]),
  plans: z.array(z.object({
    name_zh: z.string().optional().default(''),
    name_en: z.string().optional().default(''),
    price_zh: z.string().optional().default(''),
    price_en: z.string().optional().default(''),
    features_zh: z.string().optional().default(''),
    features_en: z.string().optional().default(''),
  })).optional().default([]),
});

const guideSchema = z.object({
  slug: z.string(),
  type: z.literal('guide'),
  category: z.string().optional().default('guides'),
  category_zh: z.string().optional().default('使用攻略'),
  category_en: z.string().optional().default('Guides'),
  title_zh: z.string(),
  title_en: z.string(),
  description_zh: z.string(),
  description_en: z.string(),
  author_zh: z.string().optional().default('AIFreePlan'),
  author_en: z.string().optional().default('AIFreePlan'),
  date_published: z.string(),
  date_modified: z.string(),
  tags_zh: z.array(z.string()).optional().default([]),
  tags_en: z.array(z.string()).optional().default([]),
  related_tools: z.array(z.string()).optional().default([]),
  faq_zh: z.array(z.object({ q: z.string(), a: z.string() })).optional().default([]),
  faq_en: z.array(z.object({ q: z.string(), a: z.string() })).optional().default([]),
  content_zh: z.string().optional().default(''),
  content_en: z.string().optional().default(''),
  howto_steps: z.array(z.object({
    name_zh: z.string().optional().default(''),
    name_en: z.string().optional().default(''),
    text_zh: z.string().optional().default(''),
    text_en: z.string().optional().default(''),
  })).optional().default([]),
  howto_name_zh: z.string().optional().default(''),
  howto_name_en: z.string().optional().default(''),
  howto_desc_zh: z.string().optional().default(''),
  howto_desc_en: z.string().optional().default(''),
});

const toolsCollection = defineCollection({
  type: 'content_layer',
  loader: file('src/content/tools.json'),
  schema: toolSchema,
});

const guidesCollection = defineCollection({
  type: 'content_layer',
  loader: file('src/content/guides.json'),
  schema: guideSchema,
});

export const collections = {
  tools: toolsCollection,
  guides: guidesCollection,
};
